version: "3.9"

services:
  messagebus:
    image: rabbitmq:latest
    container_name: messagebus    
    hostname: "messagebus"
    labels:
      NAME: "messagebus"

  logging:
    build: ./loggerAPI
    environment:
      - MESSAGE_QUEUE=amqp://messagebus
    volumes:
      - ./data:/data
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - messagebus


  web:
    build: ./server
    ports:
      - 3000:3000
    environment:
      - MESSAGE_QUEUE=amqp://messagebus
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - messagebus     
    