name: Deploy on Pull request 2
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches:
      - '*'
    paths-ignore:
      - "*.md"
  issue_comment:
    types: [ created, edited ]
jobs:
  deploy:
    name: Deploy Environment
    uses: bunnyshell/workflows/.github/workflows/prepare-and-deploy-env.yaml@v2
    with:
      pr-number: ${{ github.event.number || github.event.issue.number }}
      git-ref: refs/pull/${{ github.event.number || github.event.issue.number }}/head
      allowed-users: "*"
      restricted-files: |
        .bunnyshell/*
      project-id: "mBX25vnwZe"
      cluster-id: "pXMWRp4G8B"
      env-name: "Demo PR #${{ github.event.number || github.event.issue.number }}"
      bunnyshell-yaml-path: .bunnyshell/bunnyshell.yaml
      comment-on-pr: true
      deploy-as-stopped: false
    secrets:
      bunnyshell-access-token: "2717:83a656274fa4a4b6824edaeff1ca1fea"